# Generated by Django 5.0.6 on 2024-06-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade', models.PositiveSmallIntegerField()),
                ('cl', models.CharField(max_length=4)),
                ('birth', models.DateField()),
                ('score1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('score2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('score3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('status', models.CharField(choices=[('approved', 'APROVED'), ('failed', 'FAILED'), ('analysis', 'ANALYSIS'), ('undefined', 'UNDEFINED')], max_length=20)),
            ],
        ),
    ]
