# Generated by Django 5.0.6 on 2024-06-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_passwordroutine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordRoutine',
        ),
    ]
