# Generated by Django 5.0.6 on 2024-06-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_passwordroutine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordRoutine',
        ),
    ]
